# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "#holmevann1013moh"
email: carlerik+holmevann@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
    Prosjektblogg og informasjon for hytta i sørenden av Holmevann
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://holmevann.kopseng.no" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kopseng
github_username:  fatso83
google_analytics: UA-112389015-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
destination: docs

sass:
    sass_dir: assets/_sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Other custom vars
google_maps_custom_url:  https://www.google.com/maps/d/viewer?mid=1dFockLfyDNtDZ7GCysiFRs17Sh3qQIrb&usp=sharing
norgeskart_android: https://play.google.com/store/apps/details?id=no.avinet.norgeskart

cloudinary:
    cloud_name: fatso83
    verbose: true
    only_prod: true
    #origin_url: https://holmevann.kopseng.no
    presets:
        default:
            min_width: 320
            max_width: 1600
            fallback_max_width: 800
            steps: 5
            sizes: "(min-width: 50rem) 50rem, 90vw"
