[build]
  command = "asdf exec bundle exec jekyll build && asdf exec bundle exec ruby scripts/translate_site.rb"
  publish = "_site"

[[headers]]
  for = "/*.webmanifest"
  [headers.values]
    Content-Type = "application/manifest+json"
